Refactor uninstall workflow to streamline EBS service account deletion and add OIDC provider retrieval and deletion steps

diff --git a/.github/workflows/CD deploy.yml b/.github/workflows/CD deploy.yml
--- a/.github/workflows/CD deploy.yml
+++ b/.github/workflows/CD deploy.yml
@@ -118,159 +118,194 @@ jobs:
         echo "EKS_CLUSTER_ENDPOINT=${{steps.tf-outputs.outputs.eks_cluster_endpoint}}" >> $GITHUB_ENV
         echo "EKS_NODE_GROUP_NAME=${{steps.tf-outputs.outputs.aws_eks_node_group}}" >> $GITHUB_ENV
 
-#    - name: Get Kube config file
-#      id: getconfig
-#      if: steps.apply.outcome == 'success'
-#      run: aws eks update-kubeconfig --region ${{ env.AWS_REGION }} --name ${{ env.EKS_CLUSTER_NAME }}
-#  
-#    - name: Create namespace and associate IAM OIDC provider
-#      if: steps.getconfig.outcome == 'success'
-#      run: |
-#        kubectl get namespace ${NAMESPACE} || \
-#        kubectl create namespace ${NAMESPACE}
-#        
-#    - name: associate IAM OIDC provider
-#      run: |
-#        eksctl utils associate-iam-oidc-provider --cluster=$EKS_CLUSTER_NAME  --approve
-#    
+    - name: Get Kube config file
+      id: getconfig
+      if: steps.apply.outcome == 'success'
+      run: aws eks update-kubeconfig --region ${{ env.AWS_REGION }} --name ${{ env.EKS_CLUSTER_NAME }}
+  
+    - name: Create namespace and associate IAM OIDC provider
+      if: steps.getconfig.outcome == 'success'
+      run: |
+        kubectl get namespace ${NAMESPACE} || \
+        kubectl create namespace ${NAMESPACE}
+        
+    - name: associate IAM OIDC provider
+      run: |
+        eksctl utils associate-iam-oidc-provider --cluster=$EKS_CLUSTER_NAME --region $AWS_REGION  --approve
+    - name: Create IAM role and service account for EBS CSI Driver
+      run: |
+        eksctl create iamserviceaccount \
+          --cluster $EKS_CLUSTER_NAME \
+          --region $AWS_REGION \
+          --name ebs-csi-controller-sa \
+          --namespace kube-system \
+          --attach-policy-arn arn:aws:iam::aws:policy/service-role/AmazonEBSCSIDriverPolicy \
+          --override-existing-serviceaccounts \
+          --approve
 #    - name: Create IAM role for EBS CSI Driver
 #      run: |
-#        eksctl create iamserviceaccount \
-#        --name ebs-csi-controller-sa \
-#        --namespace kube-system \
-#        --cluster $EKS_CLUSTER_NAME \
-#        --attach-policy-arn arn:aws:iam::aws:policy/service-role/AmazonEBSCSIDriverPolicy \
-#        --approve \
-#        --role-only \
-#        --role-name AmazonEKS_EBS_CSI_DriverRole
-#
-#    - name: Setup EBS CSI Driver Just to have it if not exits
-#      run: |
-#        eksctl get addon --name aws-ebs-csi-driver --cluster $EKS_CLUSTER_NAME --region $AWS_REGION || \
-#        eksctl create addon --name aws-ebs-csi-driver --cluster $EKS_CLUSTER_NAME --region $AWS_REGION --service-account-role-arn arn:aws:iam::${AWS_ACCOUNT_ID}:role/AmazonEKS_EBS_CSI_DriverRole --force
-#
-#    - name: Add EFS CSI Driver Helm repo
-#      run: |
-#        helm repo add aws-efs-csi-driver https://kubernetes-sigs.github.io/aws-efs-csi-driver
-#        helm repo update
-#
-#    - name: Install EFS CSI Driver
-#      working-directory: ./files
-#      run: |
-#        envsubst < aws-efs-values.yml | helm upgrade aws-efs-csi-driver aws-efs-csi-driver/aws-efs-csi-driver --install --namespace kube-system -f -
-#        kubectl get pod -n kube-system -l "app.kubernetes.io/name=aws-efs-csi-driver,app.kubernetes.io/instance=aws-efs-csi-driver"
-#
-#    - name: Create EFS StorageClass
-#      working-directory: ./files
-#      run: |
-#        if ! kubectl get storageclass -n ${NAMESPACE} 2>/dev/null | grep -q "alfresco-efs-sc"; then
-#          envsubst < alf-efs-storage-class.yaml | kubectl create -f -
-#        fi
-#      continue-on-error: true
-#      
-#    - name: Create EFS Persistent Volume
-#      working-directory: ./files
-#      run: |
-#          kubectl get pv -n ${NAMESPACE} | grep -q "alf-content-pv" || \
-#          envsubst < alf-content-persistence-volume.yaml | kubectl apply -f -
-#      continue-on-error: true
-#      
-#    - name: Create EFS Persistent Volume Claim
-#      working-directory: ./files
-#      run: |
-#        kubectl get pvc -n ${NAMESPACE} | grep -q "alf-content-pvc" || \
-#        envsubst < alf-content-persistence-volume-claim.yaml | kubectl create -f -
-#      continue-on-error: true
-#
-#    - name: Apply External DNS configuration
-#      working-directory: ./files
-#      run: |
-#        kubectl apply -f external-dns.yaml
-#
-#    - name: Verify External DNS
-#      run: |
-#        kubectl get configmap external-dns-config -n kube-system
-#        kubectl describe configmap external-dns-config -n kube-system
-#        kubectl get pods -n kube-system -l app=external-dns
-#
-## esto no es necesario por que en terraform se esta asignando el rol con todo ya definido
-##    - name: Configure IAM Role for NodeGroup
-##        
-##      run: |
-##        # 1. Lista los Node Groups del clúster EKS
-##        NODEGROUP=$(aws eks list-nodegroups --cluster-name $EKS_CLUSTER_NAME --query "nodegroups[0]" --output text)
-##        
-##        if [ "$NODEGROUP" == "None" ]; then
-##          echo "No se encontró un grupo de nodos para el clúster $EKS_CLUSTER_NAME"
-##          exit 1
-##        fi
-##    
-##        echo "NodeGroup encontrado: $NODEGROUP"
-##    
-##        # 2. Encuentra el nombre del rol asociado al NodeGroup
-##        NODE_ROLE=$(aws eks describe-nodegroup --cluster-name $EKS_CLUSTER_NAME --nodegroup-name $NODEGROUP --query "nodegroup.nodeRole" --output text)
-##    
-##        if [ -z "$NODE_ROLE" ]; then
-##          echo "No se encontró un rol asociado al NodeGroup $NODEGROUP"
-##          exit 1
-##        fi
-##    
-##        echo "Rol de IAM encontrado: $NODE_ROLE"
-##    
-##        # 3. Adjunta la política administrada AmazonRoute53FullAccess al rol
-##        aws iam attach-role-policy --role-name $(basename $NODE_ROLE) --policy-arn arn:aws:iam::aws:policy/AmazonRoute53FullAccess
-##    
-##        echo "Política AmazonRoute53FullAccess adjuntada al rol $NODE_ROLE"
-#
-#
-#    - name: Add Ingress NGINX Helm repo
-#      run: |
-#        helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
-#        helm repo update
-#
-#    # Install Ingress Controller Generico
-##    - name: Install Ingress Controller
-##      working-directory: ./files
-##      run: |
-##        helm upgrade --install ingress-nginx ingress-nginx \
-##        --repo https://kubernetes.github.io/ingress-nginx \
-##        --namespace ingress-nginx --create-namespace \
-##        --version 4.7.2 \
-##        --set controller.allowSnippetAnnotations=true
-##
-##        helm delete ingress-nginx -n ingress-nginx
-#
-#    - name: Apply Ingress RBAC configuration
-#      working-directory: ./files
-#      run: |
-#        envsubst < ingress-rbac.yaml | kubectl apply -f - -n ${NAMESPACE}
-#
-#    - name: Install Ingress Controller
-#      run: |
-#        helm upgrade acs-ingress ingress-nginx/ingress-nginx --install --set controller.scope.enabled=true --set controller.scope.namespace=$NAMESPACE --set rbac.create=true --set controller.config."proxy-body-size"="100m" --set controller.service.targetPorts.https=80 --set controller.service.annotations."service\.beta\.kubernetes\.io/aws-load-balancer-backend-protocol"="http" --set controller.service.annotations."service\.beta\.kubernetes\.io/aws-load-balancer-ssl-ports"="https" --set controller.service.annotations."service\.beta\.kubernetes\.io/aws-load-balancer-ssl-cert"="${CERTIFICATE_ARN}" --set controller.service.annotations."external-dns\.alpha\.kubernetes\.io/hostname"="acs.${DOMAIN}" --set controller.service.annotations."service\.beta\.kubernetes\.io/aws-load-balancer-ssl-negotiation-policy"="ELBSecurityPolicy-TLS-1-2-2017-01" --set controller.publishService.enabled=true --set controller.ingressClassResource.name="$NAMESPACE-nginx" --set controller.ingressClassByName=true --atomic --namespace $NAMESPACE
+#       eksctl create iamserviceaccount \
+#       --name ebs-csi-controller-sa \
+#       --namespace kube-system \
+#       --cluster $EKS_CLUSTER_NAME \
+#       --attach-policy-arn arn:aws:iam::aws:policy/service-role/AmazonEBSCSIDriverPolicy \
+#       --approve \
+#       --role-only \
+#       --role-name AmazonEKS_EBS_CSI_DriverRole
+    - name: Get EBS CSI Role ARN from ServiceAccount
+      id: get-ebs-csi-role
+      run: |
+        # Describimos el SA para extraer la anotación con el ARN del rol
+        SA_INFO=$(kubectl describe sa ebs-csi-controller-sa -n kube-system)
+        
+        # Buscamos la línea que contenga 'eks.amazonaws.com/role-arn:'
+        ROLE_ARN=$(echo "$SA_INFO" | grep 'eks.amazonaws.com/role-arn:' | awk '{print $2}')
+        
+        if [ -z "$ROLE_ARN" ]; then
+          echo "ERROR: No se encontró la anotación 'eks.amazonaws.com/role-arn' en el ServiceAccount ebs-csi-controller-sa."
+          exit 1
+        fi
+        
+        echo "Encontrado ROLE_ARN=$ROLE_ARN"
+        
+        # Guardamos en el entorno de GitHub Actions
+        echo "ROLE_ARN=$ROLE_ARN" >> $GITHUB_ENV
+    - name: Create EBS CSI Add-on
+      run: |
+        echo "Usaremos el ARN: ${{ env.ROLE_ARN }}"
+        eksctl create addon \
+          --name aws-ebs-csi-driver \
+          --cluster $EKS_CLUSTER_NAME \
+          --region $AWS_REGION \
+          --service-account-role-arn "${{ env.ROLE_ARN }}" \
+          --force        
+    - name: Setup EBS CSI Driver Just to have it if not exits
+      run: |
+        eksctl get addon --name aws-ebs-csi-driver --cluster $EKS_CLUSTER_NAME --region $AWS_REGION || \
+        eksctl create addon --name aws-ebs-csi-driver --cluster $EKS_CLUSTER_NAME --region $AWS_REGION --service-account-role-arn arn:aws:iam::${AWS_ACCOUNT_ID}:role/AmazonEKS_EBS_CSI_DriverRole --force
+
+    - name: Add EFS CSI Driver Helm repo
+      run: |
+        helm repo add aws-efs-csi-driver https://kubernetes-sigs.github.io/aws-efs-csi-driver
+        helm repo update
+
+    - name: Install EFS CSI Driver
+      working-directory: ./files
+      run: |
+        envsubst < aws-efs-values.yml | helm upgrade aws-efs-csi-driver aws-efs-csi-driver/aws-efs-csi-driver --install --namespace kube-system -f -
+        kubectl get pod -n kube-system -l "app.kubernetes.io/name=aws-efs-csi-driver,app.kubernetes.io/instance=aws-efs-csi-driver"
+
+    - name: Create EFS StorageClass
+      working-directory: ./files
+      run: |
+        if ! kubectl get storageclass -n ${NAMESPACE} 2>/dev/null | grep -q "alfresco-efs-sc"; then
+          envsubst < alf-efs-storage-class.yaml | kubectl create -f -
+        fi
+      continue-on-error: true
+      
+    - name: Create EFS Persistent Volume
+      working-directory: ./files
+      run: |
+          kubectl get pv -n ${NAMESPACE} | grep -q "alf-content-pv" || \
+          envsubst < alf-content-persistence-volume.yaml | kubectl apply -f -
+      continue-on-error: true
+      
+    - name: Create EFS Persistent Volume Claim
+      working-directory: ./files
+      run: |
+        kubectl get pvc -n ${NAMESPACE} | grep -q "alf-content-pvc" || \
+        envsubst < alf-content-persistence-volume-claim.yaml | kubectl create -f -
+      continue-on-error: true
+
+    - name: Apply External DNS configuration
+      working-directory: ./files
+      run: |
+        kubectl apply -f external-dns.yaml
+
+    - name: Verify External DNS
+      run: |
+        kubectl get configmap external-dns-config -n kube-system
+        kubectl describe configmap external-dns-config -n kube-system
+        kubectl get pods -n kube-system -l app=external-dns
+
+# esto no es necesario por que en terraform se esta asignando el rol con todo ya definido
+#    - name: Configure IAM Role for NodeGroup
 #        
-#    - name: Verify Ingress Controller pods
-#      run: | 
-#        kubectl get pods -n ${NAMESPACE}
-#        kubectl get pods -n kube-system
-#
-#    - name: Create Docker Registry Secret if not exists
 #      run: |
-#        kubectl get secret quay-registry-secret -n ${NAMESPACE} || \
-#        kubectl create secret docker-registry quay-registry-secret \
-#          --docker-server=quay.io \
-#          --docker-username=$QUAY_USERNAME \
-#          --docker-password=$QUAY_PASSWORD \
-#          -n ${NAMESPACE}
-#      # if ! kubectl get secret quay-registry-secret -n ${NAMESPACE} 2>/dev/null; then
-#      #   kubectl create secret docker-registry quay-registry-secret \
-#      #     --docker-server=quay.io \
-#      #     --docker-username=$QUAY_USERNAME \
-#      #     --docker-password=$QUAY_PASSWORD \
-#      #     -n ${NAMESPACE}
-#      # else
-#      #   echo "Secret quay-registry-secret already exists in namespace ${NAMESPACE}"
-#      # fi
+#        # 1. Lista los Node Groups del clúster EKS
+#        NODEGROUP=$(aws eks list-nodegroups --cluster-name $EKS_CLUSTER_NAME --query "nodegroups[0]" --output text)
+#        
+#        if [ "$NODEGROUP" == "None" ]; then
+#          echo "No se encontró un grupo de nodos para el clúster $EKS_CLUSTER_NAME"
+#          exit 1
+#        fi
+#    
+#        echo "NodeGroup encontrado: $NODEGROUP"
+#    
+#        # 2. Encuentra el nombre del rol asociado al NodeGroup
+#        NODE_ROLE=$(aws eks describe-nodegroup --cluster-name $EKS_CLUSTER_NAME --nodegroup-name $NODEGROUP --query "nodegroup.nodeRole" --output text)
+#    
+#        if [ -z "$NODE_ROLE" ]; then
+#          echo "No se encontró un rol asociado al NodeGroup $NODEGROUP"
+#          exit 1
+#        fi
+#    
+#        echo "Rol de IAM encontrado: $NODE_ROLE"
+#    
+#        # 3. Adjunta la política administrada AmazonRoute53FullAccess al rol
+#        aws iam attach-role-policy --role-name $(basename $NODE_ROLE) --policy-arn arn:aws:iam::aws:policy/AmazonRoute53FullAccess
+#    
+#        echo "Política AmazonRoute53FullAccess adjuntada al rol $NODE_ROLE"
+
+
+    - name: Add Ingress NGINX Helm repo
+      run: |
+        helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
+        helm repo update
+
+    # Install Ingress Controller Generico
+#    - name: Install Ingress Controller
+#      working-directory: ./files
+#      run: |
+#        helm upgrade --install ingress-nginx ingress-nginx \
+#        --repo https://kubernetes.github.io/ingress-nginx \
+#        --namespace ingress-nginx --create-namespace \
+#        --version 4.7.2 \
+#        --set controller.allowSnippetAnnotations=true
+#
+#        helm delete ingress-nginx -n ingress-nginx
+
+    - name: Apply Ingress RBAC configuration
+      working-directory: ./files
+      run: |
+        envsubst < ingress-rbac.yaml | kubectl apply -f - -n ${NAMESPACE}
+
+    - name: Install Ingress Controller
+      run: |
+        helm upgrade acs-ingress ingress-nginx/ingress-nginx --install --set controller.scope.enabled=true --set controller.scope.namespace=$NAMESPACE --set rbac.create=true --set controller.config."proxy-body-size"="100m" --set controller.service.targetPorts.https=80 --set controller.service.annotations."service\.beta\.kubernetes\.io/aws-load-balancer-backend-protocol"="http" --set controller.service.annotations."service\.beta\.kubernetes\.io/aws-load-balancer-ssl-ports"="https" --set controller.service.annotations."service\.beta\.kubernetes\.io/aws-load-balancer-ssl-cert"="${CERTIFICATE_ARN}" --set controller.service.annotations."external-dns\.alpha\.kubernetes\.io/hostname"="acs.${DOMAIN}" --set controller.service.annotations."service\.beta\.kubernetes\.io/aws-load-balancer-ssl-negotiation-policy"="ELBSecurityPolicy-TLS-1-2-2017-01" --set controller.publishService.enabled=true --set controller.ingressClassResource.name="$NAMESPACE-nginx" --set controller.ingressClassByName=true --atomic --namespace $NAMESPACE
+        
+    - name: Verify Ingress Controller pods
+      run: | 
+        kubectl get pods -n ${NAMESPACE}
+        kubectl get pods -n kube-system
+
+    - name: Create Docker Registry Secret if not exists
+      run: |
+        kubectl get secret quay-registry-secret -n ${NAMESPACE} || \
+        kubectl create secret docker-registry quay-registry-secret \
+          --docker-server=quay.io \
+          --docker-username=$QUAY_USERNAME \
+          --docker-password=$QUAY_PASSWORD \
+          -n ${NAMESPACE}
+      # if ! kubectl get secret quay-registry-secret -n ${NAMESPACE} 2>/dev/null; then
+      #   kubectl create secret docker-registry quay-registry-secret \
+      #     --docker-server=quay.io \
+      #     --docker-username=$QUAY_USERNAME \
+      #     --docker-password=$QUAY_PASSWORD \
+      #     -n ${NAMESPACE}
+      # else
+      #   echo "Secret quay-registry-secret already exists in namespace ${NAMESPACE}"
+      # fi
 #
 #
 #    - name: Install Alfresco Content Services
